### ISSUE TITLE
Scrolling with trackpoint auto opens (clicks) on every link under pointer during scrolling

### ISSUE THREAD

**Issue by igavrysh** [tylernguyen/x1c6-hackintosh#42]
When I am scrolling with Trackpoint (trackpoint + middle button) every link under pointer (or button or any UI elements) is pressed and new tab in browser is opened.

When scrolling with touch pad this issue does not happen.

I tried other repositories like https://github.com/zhtengw/EFI-for-X1C6-hackintosh . This issue is not present there (still cannot use their version cos they have other problems, e.g. audio problems after sleep)

**Comment by tylernguyen** [comment]
@igavrysh Seems like an issue with VoodooPS2 and VoodooInput, you need to open an issue on the respective repos. https://github.com/acidanthera/VoodooPS2 and https://github.com/acidanthera/VoodooInput.

The other repo doesn't have this issue as it uses rehabman's branch of voodoops2, you can switch over to that kext branch if you prefer.

**Comment by tylernguyen** [comment]
@igavrysh My mistake, correction: the new x1c6-keyboard SSDT should correct this issue. It had to to do with how [acidanthera/VoodooPS2](https://github.com/acidanthera/VoodooPS2) handles Thinkpad_Clickpad. Feel free to close this issue once you've tried out the new EFI-OpenCore folder.

**Comment by tylernguyen** [comment]
While we’re on the same topic, you can see that there are other settings within x1c6-keyboard regarding the clickpad. Feel free to edit these and compile your own SSDT as how you prefer the trackpoint to behave.

**Comment by zacharysalvatore** [comment]
Before you fix this issue. I use aonother workaroud i found. I install a third-party app called "smart scroll" and 'suppress middle button's usual action when scrolling'
![系统偏好设置 2020-04-06 at 08 25 14@2x](https://user-images.githubusercontent.com/14255685/78514062-09443280-77e2-11ea-94c5-84ded252b36c.png)
![系统偏好设置 2020-04-06 at 08 23 45@2x](https://user-images.githubusercontent.com/14255685/78514065-106b4080-77e2-11ea-83de-8e175e7626c1.png)
![系统偏好设置 2020-04-06 at 08 24 37@2x](https://user-images.githubusercontent.com/14255685/78514068-13663100-77e2-11ea-8df1-d0c5bce4ae66.png)

**Comment by tylernguyen** [comment]
@zackerysalvatore Thank you contributing! In the future, please open an issue anytime you see a problem. I want to make this project as perfect as as possible out of the box.

**Comment by igavrysh** [comment]
Tyler thanks a lot for your great contribution!!!

**Comment by igavrysh** [comment]
Zachary, thanks for your suggestion!

**Comment by igavrysh** [comment]
The issue is resolved for my laptop, Thx for fixing it!

**Comment by Jamesxxx1997** [comment]
@tylernguyen hi! I have a different machine , thinkpad x1 yoga 2018 , and I also encounter the same issue.
Using the newest version of voodoops2 , I've also put SSDT-Thinkpad_Clickpad into ACPI/patch folder , however the middle click issue still present.
Can you give me a help? Thank you.

machine specs:
x1 yoga 2018
cpu : i7-8650u
ram : 16gb 2133 MHz DDR3
graphics : intel uhd 620
SSD : intel 760p
  
ioreg : [MacBook Pro (5).zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5091237/MacBook.Pro.5.zip)
my efi folder : https://drive.google.com/file/d/0B1uiMWvThaXnLXpBRE5MRmlOZVdtU3NxNFpaMWdobmVPcFVn/view?usp=sharing
